[simulation]
identifier = 1
bootstrap_resamples = 10000

[temperature]
max = 3.0
steps = 96

[metropolis]
num_chunks = 10
sweeps_per_chunk = 20000
sizes = [
    20, 40, 60, 80, 100, 120, 140, 160, 180, 200
]

[wolff]
num_chunks = 10
sweeps_per_chunk = 20000
sizes = [
    20, 40, 60, 80, 100, 120, 140, 160, 180, 200
]
