[simulation]
identifier = 0
bootstrap_resamples = 20000

[storage]
engine = 2 # 1 is SQLite and 2 is PostgreSQL
connection_string = "postgres://postgres:postgres@10.4.0.129:5432/Bachelor"

[temperature]
max = 3.0
steps = 48
max_depth = 1

[vortices]
sizes = [ 128 ]

[metropolis]
num_chunks = 20
sweeps_per_chunk = 100000
sizes = [
    4, 8, 16, 32, 48, 56, 64, 80, 98, 112, 128
]

[wolff]
num_chunks = 10
sweeps_per_chunk = 100000
sizes = [
    4, 8, 16, 32, 48, 56, 64, 80, 98, 112, 128
]
