[simulation]
identifier = 1
bootstrap = 100000

[metropolis]
num_chunks = 20
sweeps_per_chunk = 100000
sizes = [
    20, 40, 60, 80, 100
]

[wolff]
num_chunks = 20
sweeps_per_chunk = 10000
sizes = [
    20, 40, 60, 80, 100
]
