[simulation]
identifier = 1
bootstrap_resamples = 10000

[temperature]
max = 3.0
steps = 64

[metropolis]
num_chunks = 20
sweeps_per_chunk = 10000
sizes = [
    20, 40, 60, 80, 100
]

[wolff]
num_chunks = 10
sweeps_per_chunk = 10000
sizes = [
    20, 40, 60, 80, 100
]
