[simulation]
identifier = 1
bootstrap_resamples = 4000

[temperature]
max = 2
steps = 32

[metropolis]
num_chunks = 1
sweeps_per_chunk = 40000
sizes = [
    20, 40, 60
]

[wolff]
num_chunks = 1
sweeps_per_chunk = 40000
sizes = [
    20, 40, 60
]
