[simulation]
identifier = 1
bootstrap_resamples = 80000

[temperature]
max = 2
steps = 48

[metropolis]
num_chunks = 4
sweeps_per_chunk = 100000
sizes = [
    32, 48, 64, 80, 96, 112, 128
]

[wolff]
num_chunks = 4
sweeps_per_chunk = 100000
sizes = [
    32, 48, 64, 80, 96, 112, 128
]
