[simulation]
identifier = 1
bootstrap_resamples = 40000

[temperature]
max = 2
steps = 64

[metropolis]
num_chunks = 1
sweeps_per_chunk = 200000
sizes = [
    4, 8, 12, 16, 32, 64, 128, 256, 512, 1024
]

[wolff]
num_chunks = 1
sweeps_per_chunk = 200000
sizes = [
    4, 8, 12, 16, 32, 64, 128, 256, 512, 1024
]
