[simulation]
identifier = 2
bootstrap_resamples = 10000

[temperature]
max = 3.0
steps = 32
max_depth = 2

[vortices]
sizes = [ ]

[metropolis]
num_chunks = 1
sweeps_per_chunk = 10000
sizes = [
    4, 8, 16, 24, 32, 48, 64
]

[wolff]
num_chunks = 1
sweeps_per_chunk = 6000
sizes = [
    4, 8, 16, 24, 32, 48, 64
]
