[simulation]
identifier = 1
bootstrap_resamples = 80000

[temperature]
max = 2.0
steps = 64
max_zoom = 3

[vortices]
sizes = [ ]

[metropolis]
num_chunks = 5
sweeps_per_chunk = 80000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]

[wolff]
num_chunks = 5
sweeps_per_chunk = 40000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]
