[simulation]
identifier = 1
bootstrap_resamples = 10000

[temperature]
max = 3.0
steps = 64

[metropolis]
num_chunks = 10
sweeps_per_chunk = 100000
sizes = [
    20
]

[wolff]
num_chunks = 10
sweeps_per_chunk = 200000
sizes = [
    20
]
