[simulation]
identifier = 2
bootstrap_resamples = 10000

[temperature]
max = 3.0
steps = 32
max_depth = 2

[vortices]
sizes = [ ]

[metropolis]
num_chunks = 5
sweeps_per_chunk = 100000
sizes = [
    4, 8, 16, 24, 32
]

[wolff]
num_chunks = 5
sweeps_per_chunk = 60000
sizes = [
    4, 8, 16, 24, 32
]
