[simulation]
identifier = 1
bootstrap_resamples = 16000

[temperature]
max = 2
steps = 64

[vortices]
sizes = [ 64, 128 ]

[metropolis]
num_chunks = 2
sweeps_per_chunk = 80000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]

[wolff]
num_chunks = 2
sweeps_per_chunk = 40000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]
