[simulation]
identifier = 1
bootstrap_resamples = 80000

[temperature]
max = 2
steps = 64

[vortices]
sizes = [ 64, 128 ]

[metropolis]
num_chunks = 4
sweeps_per_chunk = 100000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]

[wolff]
num_chunks = 4
sweeps_per_chunk = 100000
sizes = [
    4, 8, 16, 32, 64, 96, 128, 160, 192
]
