[simulation]
identifier = 0
bootstrap_resamples = 10000

[storage]
engine = 1 # 1 is SQLite and 2 is PostgreSQL
connection_string = "output/data.db"

[temperature]
max = 3.0
steps = 32
max_depth = 1

[vortices]
sizes = []

[metropolis]
num_chunks = 4
sweeps_per_chunk = 50000
sizes = [
    16
]

[wolff]
num_chunks = 4
sweeps_per_chunk = 50000
sizes = [
    16
]
