// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SPINS_SCHEMAS_H_
#define FLATBUFFERS_GENERATED_SPINS_SCHEMAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace schemas {

struct Spins;
struct SpinsBuilder;

struct Spins FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpinsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<double> *data() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct SpinsBuilder {
  typedef Spins Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<double>> data) {
    fbb_.AddOffset(Spins::VT_DATA, data);
  }
  explicit SpinsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Spins> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Spins>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Spins> CreateSpins(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> data = 0) {
  SpinsBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Spins> CreateSpinsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<double>(*data) : 0;
  return schemas::CreateSpins(
      _fbb,
      data__);
}

inline const schemas::Spins *GetSpins(const void *buf) {
  return ::flatbuffers::GetRoot<schemas::Spins>(buf);
}

inline const schemas::Spins *GetSizePrefixedSpins(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schemas::Spins>(buf);
}

inline bool VerifySpinsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schemas::Spins>(nullptr);
}

inline bool VerifySizePrefixedSpinsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schemas::Spins>(nullptr);
}

inline void FinishSpinsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schemas::Spins> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSpinsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schemas::Spins> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schemas

#endif  // FLATBUFFERS_GENERATED_SPINS_SCHEMAS_H_
