// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VECTOR_SCHEMAS_H_
#define FLATBUFFERS_GENERATED_VECTOR_SCHEMAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace schemas {

struct Vector;
struct VectorBuilder;

struct Vector FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<double> *data() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct VectorBuilder {
  typedef Vector Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<double>> data) {
    fbb_.AddOffset(Vector::VT_DATA, data);
  }
  explicit VectorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector> CreateVector(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> data = 0) {
  VectorBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vector> CreateVectorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<double>(*data) : 0;
  return schemas::CreateVector(
      _fbb,
      data__);
}

inline const schemas::Vector *GetVector(const void *buf) {
  return ::flatbuffers::GetRoot<schemas::Vector>(buf);
}

inline const schemas::Vector *GetSizePrefixedVector(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schemas::Vector>(buf);
}

inline bool VerifyVectorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schemas::Vector>(nullptr);
}

inline bool VerifySizePrefixedVectorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schemas::Vector>(nullptr);
}

inline void FinishVectorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schemas::Vector> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVectorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schemas::Vector> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schemas

#endif  // FLATBUFFERS_GENERATED_VECTOR_SCHEMAS_H_
